modality:
  img:
    modality_name: img
    path: data/tcga-dataset
    feature_dim: 2048
  text:
    modality_name: text
    path: data/text_embeddings/TEXT_EMBEDDING
    feature_dim: 768
  rna:
    modality_name: rna
    path: data/RNA_embedding
    feature_dim: 256

network_type: MainModalityMoE

task_type: cls
cancer_types: UCEC
# UCEC_BLCA_LUAD_LGG_BRCA_LUSC
img_select: all

network:
  hidden_size: 512
  dropout_rate: 0.5
  pred_dim: 5    # ðŸ‘ˆ ä¸¤ç±»
  mlp_ratio: 4
  n_token: 128
  n_backbone: 8
  num_experts: 16
