modality:
  img:
    modality_name: img
    path: data/tcga-dataset
    feature_dim: 2048
    

  text:
    modality_name: text
    path: data/text_embeddings/TCGA_32types_text_embedding
    feature_dim: 768

  rna:
    modality_name: rna
    path: data/RNA_embedding/TCGA_32types_embeddings_2048
    feature_dim: 256

network_type: MultFusion

task_type: surv
cancer_type: UCEC
img_select: all

network:
  hidden_size: 128
  dropout_rate: 0.5
  pred_dim: 4
  mlp_ratio: 4
  n_token: 16